"""articles

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-17 19:46:12.044946

"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('journal', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('volume', sa.String(length=64), nullable=True),
    sa.Column('issue', sa.String(length=64), nullable=True),
    sa.Column('pages', sa.String(length=64), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('file_ref', sa.JSON(), nullable=True),
    sa.Column('file_type', sa.String(length=64), nullable=True),
    sa.Column('study_design', sa.String(length=64), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('conflict_of_interest', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_articles_doi', ['doi'], unique=False)
        batch_op.create_index('ix_articles_user_project', ['user_id', 'project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_user_project')
        batch_op.drop_index('ix_articles_doi')

    op.drop_table('articles')
    # ### end Alembic commands ###
