"""highlights notes

Revision ID: 0003
Revises: 0002
Create Date: 2026-05-17 22:07:49.658348

"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_notes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('article_id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_notes_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_article_notes_article_user', ['article_id', 'user_id'], unique=True)

    op.create_table('highlights',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('article_id', sa.String(length=32), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('colour', sa.String(length=16), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('bounding_coords', sa.JSON(), nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.create_index('ix_highlights_article_page', ['article_id', 'page_number'], unique=False)
        batch_op.create_index('ix_highlights_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_index('ix_highlights_user')
        batch_op.drop_index('ix_highlights_article_page')

    op.drop_table('highlights')
    with op.batch_alter_table('article_notes', schema=None) as batch_op:
        batch_op.drop_index('uq_article_notes_article_user')
        batch_op.drop_index(batch_op.f('ix_article_notes_user_id'))

    op.drop_table('article_notes')
    # ### end Alembic commands ###
