"""manuscript sections

Revision ID: 0004
Revises: 0003
Create Date: 2026-05-17 23:38:51.762308

"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manuscript_sections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('section_name', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manuscript_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manuscript_sections_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_manuscript_section_project_user_section', ['project_id', 'user_id', 'section_name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manuscript_sections', schema=None) as batch_op:
        batch_op.drop_index('uq_manuscript_section_project_user_section')
        batch_op.drop_index(batch_op.f('ix_manuscript_sections_user_id'))

    op.drop_table('manuscript_sections')
    # ### end Alembic commands ###
