"""abbreviations

Revision ID: 0005
Revises: 0004
Create Date: 2026-05-18 00:15:11.186239

"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abbreviations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('short_form', sa.String(length=32), nullable=False),
    sa.Column('long_form', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abbreviations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abbreviations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_abbreviation_project_user_short', ['project_id', 'user_id', 'short_form'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abbreviations', schema=None) as batch_op:
        batch_op.drop_index('uq_abbreviation_project_user_short')
        batch_op.drop_index(batch_op.f('ix_abbreviations_user_id'))

    op.drop_table('abbreviations')
    # ### end Alembic commands ###
